name: ntp_dart
description: A lightweight, cross-platform NTP client for Dart & Flutter. Fetches highly accurate time via native UDP and Web HTTP fallbacks with microsecond precision and secure caching.
version: 1.3.1
homepage: https://github.com/enzo-desimone/ntp_dart

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  http: ^1.6.0
  intl: ^0.20.2

dev_dependencies:
  test: ^1.31.1
  flutter_lints: ^6.0.0
